FROM ruby:latest@sha256:9f5ff03fb157ad4fec90a7d8c953342e592700e984c5e28feb3eea609da0e69c
LABEL Description="Ruby Programming Language for Windows" Vendor="Ruby" Version="2.2.3-x64"
RUN C:\ruby\bin\gem install rails
