FROM ruby:latest@sha256:2c45f5e02cf187019825fe5637152d2f53f50efa5a0b3549cd323500945f55ca
LABEL Description="Ruby Programming Language for Windows" Vendor="Ruby" Version="2.2.3-x64"
RUN C:\ruby\bin\gem install rails
